---
# =============================================================================
# handlers/main.yml
# =============================================================================
- name: Recreate jupyterhub stack
  community.docker.docker_compose_v2:
    project_src: "{{ jupyterhub_base_dir }}"
    state: present
    recreate: auto
  when: jupyterhub_run | bool
  listen: restart jupyterhub
